name: Validate canonical paths JSON

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate canonical paths against JSON Schema
        uses: cardinalby/schema-validator-action@v2
        with:
          file: 'canonical_paths.json'
          schema: 'canonical_paths.schema.json'
